routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

$router->group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

/**
 * Frontend Router
 */
$router->group([
    'namespace' => 'Frontend',
    'middleware' => []], function () use ($router) {

    $router->get('/', 'HomeController@index')->name('home');
    $router->get('/language/{locale}', 'HomeController@changeLanguage')->name('change_language');
    $router->get('/search', 'HomeController@search')->name('search');

    $router->get('/blog/all', 'PostController@list')->name('post_list_all');
    $router->get('/blog/{cat_slug}', 'PostController@list')->where('cat_slug', '[a-zA-Z0-9-_]+')->name('post_list');
    $router->get('/post/{slug}-{id}', 'PostController@detail')
        ->where('slug', '[a-zA-Z0-9-_]+')
        ->where('id', '[0-9]+')->name('post_detail');

    $router->get('/page/contact', 'HomeController@pageContact')->name('page_contact');
    $router->post('/page/contact', 'HomeController@sendContact')->name('page_contact_send');

    $router->get('/page/landing/{page_number}', 'HomeController@pageLanding')->name('page_landing');

    $router->get('/city/{slug}', 'CityController@detail')->name('city_detail');
    $router->get('/city/{slug}/{cat_slug}', 'CityController@detail')->name('city_category_detail');

    $router->get('/place/{slug}', 'PlaceController@detail')->name('place_detail');
    $router->get('/new-place', 'PlaceController@pageAddNew')->name('place_addnew');
    $router->get('/edit-place/{id}', 'PlaceController@pageAddNew')->name('place_edit')->middleware('auth');
    $router->post('/place', 'PlaceController@create')->name('place_create')->middleware('auth');
    $router->put('/place', 'PlaceController@update')->name('place_update')->middleware('auth');
    $router->get('/places/filter', 'PlaceController@getListFilter')->name('place_get_list_filter');

    $router->post('/review', 'ReviewController@create')->name('review_create')->middleware('auth');
    $router->post('/wishlist', 'UserController@addWishlist')->name('add_wishlist')->middleware('auth');
    $router->delete('/wishlist', 'UserController@removeWishlist')->name('remove_wishlist')->middleware('auth');

    $router->get('/user/profile', 'UserController@pageProfile')->name('user_profile')->middleware('auth');
    $router->put('/user/profile', 'UserController@updateProfile')->name('user_profile_update')->middleware('auth');
    $router->put('/user/profile/password', 'UserController@updatePassword')->name('user_password_update')->middleware('auth');
    $router->get('/user/reset-password', 'UserController@pageResetPassword')->name('user_reset_password');
    $router->put('/user/reset-password', 'ResetPasswordController@reset')->name('user_update_password');

    $router->get('/user/my-place', 'UserController@pageMyPlace')->name('user_my_place')->middleware('auth');
    $router->delete('/user/my-place', 'UserController@deleteMyPlace')->name('user_my_place_delete')->middleware('auth');

    $router->get('/user/wishlist', 'UserController@pageWishList')->name('user_wishlist')->middleware('auth');

    $router->post('/bookings', 'BookingController@booking')->name('booking_submit');

    $router->get('/auth/{social}', 'SocialAuthController@redirect')->name('login_social');
    $router->get('/auth/{social}/callback', 'SocialAuthController@callback')->name('login_social_callback');

    $router->get('/ajax-search', 'HomeController@ajaxSearch');
    $router->get('/ajax-search-listing', 'HomeController@searchListing');
    $router->get('/search', 'HomeController@search')->name('search');
    $router->get('/places/map', 'PlaceController@getListMap')->name('place_get_list_map');

    $router->get('/cities/{country_id}', 'CityController@getListByCountry')->name('city_get_list');
    $router->get('/cities', 'CityController@search')->name('city_search');

    $router->get('/search-listing-input', 'HomeController@searchListing')->name('search_listing');
    $router->get('/search-listing', 'HomeController@pageSearchListing')->name('page_search_listing');
    $router->get('/category/{slug}', 'CategoryController@listPlace')->name('category_list');
    $router->get('/categories', 'CategoryController@search')->name('category_search');

});

/*
 * AdminCP Router
 */
$router->group([
    'prefix' => 'admincp',
    'namespace' => 'Admin',
    'as' => 'admin_',
    'middleware' => ['auth', 'auth.admin']], function () use ($router) {

    $router->get('/', 'DashboardController@index')->name('dashboard');

    $router->get('/country', 'CountryController@list')->name('country_list');
    $router->post('/country', 'CountryController@create')->name('country_create');
    $router->put('/country', 'CountryController@update')->name('country_update');
    $router->delete('/country/{id}', 'CountryController@destroy')->name('country_delete');

    $router->get('/city', 'CityController@list')->name('city_list');
    $router->post('/city', 'CityController@create')->name('city_create');
    $router->put('/city', 'CityController@update')->name('city_update');
    $router->put('/city/status', 'CityController@updateStatus')->name('city_update_status');
    $router->delete('/city/{id}', 'CityController@destroy')->name('city_delete');

    $router->get('/category/{type}', 'CategoryController@list')->name('category_list');
    $router->post('/category', 'CategoryController@create')->name('category_create');
    $router->put('/category', 'CategoryController@update')->name('category_update');
    $router->delete('/category/{id}', 'CategoryController@destroy')->name('category_delete');

    $router->get('/amenities', 'AmenitiesController@list')->name('amenities_list');
    $router->post('/amenities', 'AmenitiesController@create')->name('amenities_create');
    $router->put('/amenities', 'AmenitiesController@update')->name('amenities_update');
    $router->delete('/amenities/{id}', 'AmenitiesController@destroy')->name('amenities_delete');

    $router->get('/place-type', 'PlaceTypeController@list')->name('place_type_list');
    $router->post('/place-type', 'PlaceTypeController@create')->name('place_type_create');
    $router->put('/place-type', 'PlaceTypeController@update')->name('place_type_update');
    $router->delete('/place-type/{id}', 'PlaceTypeController@destroy')->name('place_type_delete');

    $router->get('/place', 'PlaceController@list')->name('place_list');
    $router->get('/place/add', 'PlaceController@createView')->name('place_create_view');
    $router->get('/place/edit/{id}', 'PlaceController@createView')->name('place_edit_view');
    $router->post('/place', 'PlaceController@create')->name('place_create');
    $router->put('/place', 'PlaceController@update')->name('place_update');
    $router->delete('/place/{id}', 'PlaceController@destroy')->name('place_delete');

    $router->get('/review', 'ReviewController@list')->name('review_list');
    $router->delete('/review', 'ReviewController@destroy')->name('review_delete');

    $router->get('/users', 'UserController@list')->name('user_list');

    $router->get('/blog', 'PostController@list')->name('post_list_blog');
    $router->get('/pages', 'PostController@list')->name('post_list_page');

    $router->get('/posts/add/{type}', 'PostController@pageCreate')->name('post_add');
    $router->get('/posts/{id}', 'PostController@pageCreate')->name('post_edit');
    $router->post('/posts', 'PostController@create')->name('post_create');
    $router->put('/posts', 'PostController@update')->name('post_update');
    $router->delete('/posts/{id}', 'PostController@destroy')->name('post_delete');

    $router->get('/post-test', 'PostController@createPostTest');
    $router->get('/language/copy-folder', 'LanguageController@testCopyFolder');

    $router->get('/bookings', 'BookingController@list')->name('booking_list');
    $router->put('/bookings', 'BookingController@updateStatus')->name('booking_update_status');

    $router->get('/settings', 'SettingController@index')->name('settings');
    $router->post('/settings', 'SettingController@store')->name('setting_create');

    $router->get('/settings/language', 'SettingController@pageLanguage')->name('settings_language');
    $router->get('/settings/translation', 'SettingController@pageTranslation')->name('settings_translation');

    $router->put('/settings/language/status/{code}', 'LanguageController@updateStatus')->name('settings_language_status');
    $router->put('/settings/language/default', 'LanguageController@updateStatus')->name('settings_language_default');


    $router->get('/upgrade-to-v110', 'UpgradeController@upgradeToVersion110')->name('upgrade_v110');
    $router->get('/upgrade-to-v112', 'UpgradeController@upgradeToVersion112')->name('upgrade_v112');
    $router->get('/upgrade-to-v114', 'UpgradeController@upgradeToVersion114')->name('upgrade_v114');


    $router->get('/testimonials', 'TestimonialController@list')->name('testimonial_list');
    $router->get('/testimonials/add', 'TestimonialController@pageCreate')->name('testimonial_page_add');
    $router->get('/testimonials/edit/{id}', 'TestimonialController@pageCreate')->name('testimonial_page_edit');
    $router->post('/testimonials', 'TestimonialController@create')->name('testimonial_action');
    $router->put('/testimonials', 'TestimonialController@update')->name('testimonial_action');

});

$router->get('/admincp/login', 'Admin\UserController@loginPage')->name('admin_login');

app/Http/Controllers/Frontend/CityController.php
<?php

namespace App\Http\Controllers\Frontend;


use App\Http\Controllers\Controller;
use App\Models\Amenities;
use App\Models\Category;
use App\Models\City;
use App\Models\Place;
use App\Models\PlaceType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CityController extends Controller
{
    private $city;

    public function __construct(City $city)
    {
        $this->city = $city;
    }

    public function list()
    {

    }

    public function detail(Request $request, $slug, $cat_slug = null)
    {
        /**
         * Get info city
         */
        $city = $this->city->getBySlug($slug);
        if (!$city) abort(404);

        /**
         * Menu category
         */
        $categories = Category::query()
//            ->with('places')
            ->where('categories.status', Category::STATUS_ACTIVE)
            ->join('places', 'places.category', 'like', DB::raw("CONCAT('%', categories.id, '%')"))
            ->select('categories.id as id', 'categories.name as name', 'categories.priority as priority', 'categories.slug as slug', DB::raw("count(places.category) as place_count"))
            ->groupBy('categories.id')
            ->orderBy('categories.priority')
            ->get();

        /**
         * Loop categories feature and its places
         */
        $category_features = Category::query()
            ->where('is_feature', Category::IS_FEATURE)
            ->where('status', Category::STATUS_ACTIVE)
            ->get(['id', 'name', 'slug', 'feature_title']);
        $features = [];
        foreach ($category_features as $cat) {
            $places = Place::query()
                ->with('place_types')
                ->withCount('reviews')
                ->with('avgReview')
                ->withCount('wishList')
                ->where('city_id', $city->id)
                ->where('category', 'like', '%' . $cat->id . '%')
                ->where('status', Place::STATUS_ACTIVE)
                ->get();
            $features[] = [
                'category_id' => $cat->id,
                'category_name' => $cat->name,
                'category_slug' => $cat->slug,
                'feature_title' => $cat->feature_title,
                'places' => $places,
            ];
        }

        /**
         * Get places of category when user click to menu category
         */
        $places_by_category = [];
        $place_types = null;
        $amenities = null;
        if ($cat_slug) {
            $cat = Category::query()
                ->where('slug', $cat_slug)
                ->where('status', Category::STATUS_ACTIVE)
                ->first(['id', 'name', 'slug']);

            $places_by_category['category'] = $cat;
            $places_by_category['places'] = Place::query()
                ->with('place_types')
                ->withCount('reviews')
                ->with('avgReview')
                ->withCount('wishList')
                ->where('city_id', $city->id)
                ->where('category', 'like', '%' . $cat->id . '%')
                ->where('status', Place::STATUS_ACTIVE)
                ->paginate();

            $place_types = PlaceType::query()->get();

            $amenities = Amenities::query()->get();
        }

        /**
         * Block: Explorer Other Cities
         */
        $other_cities = Cache::remember('other_cities', 60 * 60, function () use ($city) {
            return City::query()
                ->withCount('places')
                ->with('country')
                ->where('status', City::STATUS_ACTIVE)
                ->where('id', '<>', $city->id)
                ->inRandomOrder()
                ->limit(4)
                ->get();
        });

//        return $places_by_category;

        /**
         * SEO Meta
         */
        $title = $city->seo_title ? $city->seo_title : $city->name;
        $description = $city->seo_description ? $city->seo_description : Str::limit($city->description, 165);
        SEOMeta($title, $description, getImageUrl($city->banner));

        return view('frontend.city.city_detail', [
            'city' => $city,
            'categories' => $categories,
            'features' => $features,
            'places_by_category' => $places_by_category,
            'other_cities' => $other_cities,
            'cat_slug' => $cat_slug,
            'place_types' => $place_types,
            'amenities' => $amenities,
        ]);
    }

    public function getListByCountry($country_id)
    {
        $cities = City::query();
        if ($country_id) {
            $cities->where('country_id', $country_id);
        }
        $cities = $cities->orderBy('created_at', 'desc')->get();
        return $cities;
    }

    public function search(Request $request)
    {
        $keyword = $request->keyword;

        $cities = City::query();

        if (isset($keyword)) {
            $cities->whereTranslationLike('name', "%{$keyword}%");
        }

        $cities = $cities->limit(20)->get();

        return $cities;
    }
}

app/Http/Controllers/Frontend/PostController.php
<?php

namespace App\Http\Controllers\Frontend;


use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Support\Facades\DB;

class PostController extends Controller
{
    public function list($cat_slug = null)
    {
        $categories = Category::query()
            ->where('categories.type', Category::TYPE_POST)
            ->where('categories.status', Category::STATUS_ACTIVE)
            ->join('posts', 'posts.category', 'like', DB::raw("CONCAT('%', categories.id, '%')"))
            ->select('categories.id as id', 'categories.name as name', 'categories.slug as slug', DB::raw("count(posts.category) as post_count"))
            ->groupBy('categories.id')
            ->orderBy('categories.name')
            ->get();

        $posts = Post::query()
            ->with('categories')
            ->with('user')
            ->where('type', Post::TYPE_BLOG)
            ->where('status', Post::STATUS_ACTIVE);

        $category = null;
        if ($cat_slug) {
            $category = Category::query()->where('slug', $cat_slug)->first();
            $posts->where('category', 'like', "%{$category->id}%");
        }

        $posts = $posts->paginate(15);

        $post_total = Post::query()
            ->where('type', Post::TYPE_BLOG)
            ->where('status', Post::STATUS_ACTIVE)
            ->count();

        // SEO Meta
        if ($category) {
            $title = $category->seo_title ? $category->seo_title : $category->name;
            $description = $category->seo_description ? $category->seo_description : '';
        } else {
            $title = "Blog";
            $description = "";
        }
        SEOMeta($title, $description);

        return view('frontend.post.blog_list', [
            'categories' => $categories,
            'category' => $category,
            'posts' => $posts,
            'post_total' => $post_total,
            'cat_slug' => $cat_slug,
        ]);
    }

    public function detail($slug, $id)
    {
        $post = Post::query()
            ->with('categories')
            ->with('user')
            ->where('id', $id)
            ->first();

        if (!$post) abort(404);

        $related_posts = Post::query()
            ->with('categories')
            ->where('type', Post::TYPE_BLOG)
            ->limit(3)
            ->get();

        ($post->type === Post::TYPE_BLOG) ? $view_name = "frontend.post.blog_detail" : $view_name = "frontend.post.page_detail";

        // SEO Meta
        $title = $post->seo_title ? $post->seo_title : $post->title;
        $description = $post->seo_description ? $post->seo_description : '';
        SEOMeta($title, $description);

        return view($view_name, [
            'post' => $post,
            'related_posts' => $related_posts,
        ]);
    }
}

resources/views/frontend/home/home_01.blade.php
@php
    $img_home_banner = getImageUrl(setting('home_banner'));
    $img_home_banner_app = getImageUrl(setting('home_banner_app'));
    if (setting('home_banner')) {
        $home_banner = "style=background-image:url({$img_home_banner})";
    } else {
        $home_banner = "style=background-image:url(/assets/images/top-banner.png)";
    }
    if (setting('home_banner_app')) {
        $home_banner_app = "style=background-image:url({$img_home_banner_app})";
    } else {
        $home_banner_app = "style=background-image:url(/assets/images/banner-apps.jpg)";
    }
@endphp
@extends('frontend.layouts.template')
@section('main')
    <main id="main" class="site-main">
        <div class="site-banner" {{$home_banner}}>
            <div class="container">
                <div class="site-banner__content golo-ajax-search">
                    <h1 class="site-banner__title">{{__('Explore the world')}}</h1>
                    <form action="{{route('search')}}" class="site-banner__search">
                        <div class="site-banner__search__field">
                            <span class="site-banner__search__icon">
                                <i class="la la-search la-24"></i>
                            </span><!-- .site-banner__search__icon -->
                            <input class="site-banner__search__input" type="text" name="keyword" placeholder="{{__('Type a city or location')}}" autocomplete="off">
                            <div class="search-result"></div>
                            <div class="golo-loading-effect"><span class="golo-dual-ring"></span></div>
                        </div><!-- .site-banner__search__input -->
                    </form><!-- .site-banner__search -->
                    <p class="site-banner__meta">
                        <span>{{__('Popular:')}}</span>
                        @foreach($popular_search_cities as $city)
                            <a href="{{route('city_detail', $city->slug)}}" title="{{$city->name}}">{{$city->name}}</a>
                        @endforeach
                    </p><!-- .site-banner__meta -->
                </div><!-- .site-banner__content -->
            </div>
        </div><!-- .site-banner -->
        <div class="cities">
            <div class="container">
                <h2 class="cities__title title">{{__('Popular cities')}}</h2>
                <div class="cities__content">
                    <div class="row">
                        @foreach($popular_cities as $city)
                            <div class="col-lg-3 col-sm-6">
                                <div class="cities__item hover__box">
                                    <div class="cities__thumb hover__box__thumb">
                                        <a title="London" href="{{route('city_detail', $city->slug)}}">
                                            <img src="{{getImageUrl($city->thumb)}}" alt="{{$city->name}}">
                                        </a>
                                    </div>
                                    <h4 class="cities__name">{{$city['country']['name']}}</h4>
                                    <div class="cities__info">
                                        <h3 class="cities__capital">{{$city->name}}</h3>
                                        <p class="cities__number">{{$city->places_count}} {{__('places')}}</p>
                                    </div>
                                </div><!-- .cities__item -->
                            </div>
                        @endforeach
                    </div>
                </div><!-- .cities__content -->
            </div>
        </div><!-- .cities -->
        <div class="banner-apps" {{$home_banner_app}}>
            <div class="container">
                <div class="banner-apps__content">
                    <h2 class="banner-apps__title">{{__('Get the App')}}</h2>
                    <p class="banner-apps__desc">{{__('Download the app and go to travel the world.')}}</p>
                    <div class="banner-apps__download">
                        <a title="App Store" href="#" class="banner-apps__download__iphone"><img src="{{asset('assets/images/assets/app-store.png')}}" alt="App Store"></a>
                        <a title="Google Play" href="#" class="banner-apps__download__android"><img src="{{asset('assets/images/assets/google-play.png')}}" alt="Google Play"></a>
                    </div>
                </div>
            </div>
        </div><!-- .banner-apps -->
        <div class="news">
            <div class="container">
                <h2 class="news__title title title--more">
                    {{__('Related stories')}}
                    <a href="{{route('post_list_all')}}" title="{{__('View more')}}">
                        {{__('View more')}}
                        <svg xmlns="http://www.w3.org/2000/svg" width="6" height="10" viewBox="0 0 6 10">
                            <path fill="#23D3D3" fill-rule="nonzero" d="M5.356 4.64L.862.148A.503.503 0 1 0 .148.86l4.137 4.135L.148 9.132a.504.504 0 1 0 .715.713l4.493-4.492a.509.509 0 0 0 0-.713z"/>
                        </svg>
                    </a>
                </h2>
                <div class="news__content">
                    <div class="row">
                        @foreach($blog_posts as $post)
                            <div class="col-md-4">
                                <article class="post hover__box">
                                    <div class="post__thumb hover__box__thumb">
                                        <a title="{{$post->title}}" href="{{route('post_detail', [$post->slug, $post->id])}}"><img src="{{getImageUrl($post->thumb)}}" alt="{{$post->title}}"></a>
                                    </div>
                                    <div class="post__info">
                                        <ul class="post__category">
                                            @foreach($post['categories'] as $cat)
                                                <li><a title="{{$cat->name}}" href="{{route('post_list', $cat->slug)}}">{{$cat->name}}</a></li>
                                            @endforeach
                                        </ul>
                                        <h3 class="post__title"><a title="{{$post->title}}" href="{{route('post_detail', [$post->slug, $post->id])}}">{{$post->title}}</a></h3>
                                    </div>
                                </article>
                            </div>
                        @endforeach

                    </div>
                </div>
            </div>
        </div><!-- .news -->
    </main><!-- .site-main -->
@stop